const hardcodedData = [
  {
    timestamp: "2025-10-20 09:15:30",
    name: "Budi Santoso",
    contact: "081...",
    subject: "Perbaikan Jalan",
    message: "Jalan dusun perlu diperbaiki...",
  },
  {
    timestamp: "2025-10-21 14:30:15",
    name: "Citra Dewi",
    contact: "citra@mail.com",
    subject: "Fasilitas Umum",
    message: "Usul penambahan tempat sampah...",
  },
  {
    timestamp: "2025-10-22 08:00:00",
    name: "Eka Wijaya",
    contact: "085...",
    subject: "Keamanan",
    message: "Perlunya ronda malam...",
  },
  {
    timestamp: "2025-10-23 09:00:00",
    name: "Gita Permata",
    contact: "gita@mail.net",
    subject: "Perbaikan Jalan",
    message: "Mohon segera ditindaklanjuti.",
  },
  {
    timestamp: "2025-10-24 10:00:00",
    name: "Indah Sari",
    contact: "089...",
    subject: "Kebersihan",
    message: "Jadwal gotong royong...",
  },
  {
    timestamp: "2025-10-24 13:45:00",
    name: "Joko Susilo",
    contact: "joko@mail.org",
    subject: "Fasilitas Umum",
    message: "Lampu penerangan jalan mati.",
  },
  {
    timestamp: "2025-10-25 08:30:00",
    name: "Kartika Putri",
    contact: "082...",
    subject: "Perbaikan Jalan",
    message: "Jalan berlubang di dekat RT 01.",
  },
  {
    timestamp: "2025-10-25 11:00:00",
    name: "Leo Chandra",
    contact: "087...",
    subject: "Kegiatan Pemuda",
    message: "Usul kegiatan karang taruna.",
  },
  {
    timestamp: "2025-10-26 10:00:00",
    name: "Maya Anggraini",
    contact: "maya@mail.co",
    subject: "Lainnya",
    message: "Ucapan terima kasih untuk KKN.",
  },
  {
    timestamp: "2025-10-19 10:00:00",
    name: "Zahra Nuraini",
    contact: "zahra@mail.com",
    subject: "Fasilitas Umum",
    message: "Perbaikan taman bermain anak.",
  },
  {
    timestamp: "2025-10-18 15:20:00",
    name: "Yudi Pratama",
    contact: "081...",
    subject: "Keamanan",
    message: "Saran pemasangan CCTV.",
  },
  {
    timestamp: "2025-10-17 09:05:00",
    name: "Xavier Simanjuntak",
    contact: "xavier@mail.net",
    subject: "Perbaikan Jalan",
    message: "Aspal mengelupas di tikungan.",
  },
  {
    timestamp: "2025-10-16 11:55:00",
    name: "Wulan Anggraini",
    contact: "085...",
    subject: "Kebersihan",
    message: "Pengelolaan sampah perlu ditingkatkan.",
  },
  {
    timestamp: "2025-10-26 14:00:00",
    name: "Nadia Utami",
    contact: "nadia@mail.id",
    subject: "Lainnya",
    message: "Pertanyaan tentang website.",
  },
];
